name: 'simple_transformer_nope'

model:
  _target_: src.models.trafo_predictor.TransformerPredictor
  input_dim: 10
  model_dim: 32
  num_heads: 1
  num_classes: 10
  num_layers: 1
  dropout: 0.0
  if_pe: False


